spring:
  datasource:
    # 1. DB 접속 주소 (biz_busy 스키마 이름 확인)
    url: jdbc:mysql://localhost:3306/biz_busy?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    # 2. 본인 MySQL 아이디/비번
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false
    show-sql: true      # 실행되는 SQL 로그 보기
    hibernate:
      ddl-auto: validate

logging:
  level:
    org.hibernate.sql: debug # SQL 쿼리 자세히 보기