spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

    # IP: 192.168.28.80 / DB이름: RanDi
    url: jdbc:mysql://192.168.28.80:3306/RanDi?serverTimezone=Asia/Seoul&characterEncoding=UTF-8

    # 계정 정보
    username: randies
    password: ktaivle0909!

  jpa:
    hibernate:
      # 중요: 'update'로 설정하면 기존 데이터를 유지하면서 테이블만 생성/수정
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect